const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('studioNative', {
  captureInfo:()=>ipcRenderer.invoke('studio:capture-info'),
  cameraSignal:value=>ipcRenderer.send('tools:camera-signal',value),
  onCameraSignal:callback=>ipcRenderer.on('tools:camera-signal',(_e,value)=>callback(value)),
  toggleDesktopTools:value=>ipcRenderer.invoke('studio:tools-toggle',value),
  updateDesktopTools:value=>ipcRenderer.send('studio:tools-state',value),
  onToolsCommand:callback=>ipcRenderer.on('studio:tools-command',(_e,value)=>callback(value)),
  onToolsAnnotations:callback=>ipcRenderer.on('studio:tools-annotations',(_e,value)=>callback(value)),
  onToolsNotes:callback=>ipcRenderer.on('studio:tools-notes',(_e,value)=>callback(value)),
  transcribe: (bytes,options) => ipcRenderer.invoke('studio:transcribe',bytes,options),
  speechModels: () => ipcRenderer.invoke('studio:speech-models'),
  downloadSpeechModel: id => ipcRenderer.invoke('studio:download-speech-model',id),
  cancelModelDownload: () => ipcRenderer.invoke('studio:cancel-model-download'),
  removeSpeechModel: id => ipcRenderer.invoke('studio:remove-speech-model',id),
  onModelProgress: callback => {const listener=(_event,value)=>callback(value);ipcRenderer.on('studio:model-progress',listener);return()=>ipcRenderer.removeListener('studio:model-progress',listener);},
  cancelSpeech: () => ipcRenderer.invoke('studio:cancel-speech'),
  onSpeechProgress: callback => {const listener=(_event,value)=>callback(value);ipcRenderer.on('studio:speech-progress',listener);return()=>ipcRenderer.removeListener('studio:speech-progress',listener);},
  saveProject: (files,saveAs=false) => ipcRenderer.invoke('studio:save-project', files,saveAs),
  openProject: () => ipcRenderer.invoke('studio:open-project'),
  pendingProject: () => ipcRenderer.invoke('studio:pending-project'),
  forgetProject: () => ipcRenderer.invoke('studio:forget-project'),
  onProjectAvailable: callback => ipcRenderer.on('studio:project-available',()=>callback()),
  encodeMp4: bytes => ipcRenderer.invoke('studio:encode', bytes),
  cancelEncode: () => ipcRenderer.invoke('studio:cancel-encode')
});
