import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const targets=await(await fetch('http://127.0.0.1:9226/json')).json(),socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(resolve=>socket.onopen=resolve);let sequence=0;const pending=new Map();socket.onmessage=event=>{const message=JSON.parse(event.data);if(pending.has(message.id)){const[resolve,reject]=pending.get(message.id);pending.delete(message.id);message.error?reject(message.error):resolve(message.result);}};
const call=(method,params={})=>{const id=++sequence,promise=new Promise((resolve,reject)=>pending.set(id,[resolve,reject]));socket.send(JSON.stringify({id,method,params}));return promise;};const evaluate=async expression=>{const result=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(JSON.stringify(result.exceptionDetails));return result.result.value;};const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{
  await evaluate(`document.querySelector('#mode-edit').click()`);await delay(600);await evaluate(`document.querySelector('#segments button').click()`);await delay(300);await evaluate(`document.querySelector('#properties-captions').click()`);await delay(200);
  assert.equal(await evaluate(`document.querySelectorAll('#caption-model option').length`),6);assert.match(await evaluate(`document.querySelector('#caption-model-detail').textContent`),/尚未下載/);
  await evaluate(`document.querySelector('#caption-provider').value='api';document.querySelector('#caption-provider').dispatchEvent(new Event('change'))`);assert.equal(await evaluate(`document.querySelector('#caption-api-settings').hidden`),false);assert.equal(await evaluate(`document.querySelector('#caption-api-key').getAttribute('autocomplete')`),'off');
  await evaluate(`document.querySelector('#caption-provider').value='local';document.querySelector('#caption-provider').dispatchEvent(new Event('change'));document.querySelector('#caption-add').click()`);for(let i=0;i<80&&await evaluate(`document.querySelector('#play').disabled`);i++)await delay(100);await evaluate(`document.querySelector('#seek').value=0;document.querySelector('#seek').dispatchEvent(new Event('input'))`);await delay(300);
  await evaluate(`document.querySelector('#play').click()`);for(let i=0;i<80&&await evaluate(`document.querySelector('#play').textContent!=='暫停'`);i++)await delay(100);assert.equal(await evaluate(`document.querySelector('#play').textContent`),'暫停');await delay(250);const before=Number(await evaluate(`document.querySelector('#seek').value`));
  await evaluate(`(()=>{const field=document.querySelector('#caption-preset');field.value='outline';field.dispatchEvent(new Event('change'));})()`);await delay(500);const after=Number(await evaluate(`document.querySelector('#seek').value`));assert.ok(after>before+.15);assert.equal(await evaluate(`document.querySelector('#play').textContent`),'暫停');assert.equal(await evaluate(`document.querySelector('#caption-style-preview').dataset.preset`),'outline');
  await evaluate(`document.querySelector('.caption-recognition').open=true;document.querySelector('.inspector').scrollTop=0`);await delay(100);const captionScreenshot=await call('Page.captureScreenshot');await writeFile('/tmp/eduvideo-v5-caption-panel.png',Buffer.from(captionScreenshot.data,'base64'));
  await evaluate(`(()=>{document.querySelector('#properties-clip').click();const field=document.querySelector('#clip-volume');field.value='35';field.dispatchEvent(new Event('input'));})()`);await delay(500);assert.equal(await evaluate(`document.querySelector('#play').textContent`),'暫停');assert.ok(Number(await evaluate(`document.querySelector('#seek').value`))>after+.15);
  const person=await evaluate(`(()=>{const r=document.querySelector('#canvas').getBoundingClientRect();return{x:r.x+r.width*.85,y:r.y+r.height*.75};})()`);await call('Input.dispatchMouseEvent',{type:'mousePressed',...person,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',...person,button:'left',clickCount:1});await delay(250);assert.equal(await evaluate(`document.querySelector('#play').textContent`),'暫停');assert.equal(await evaluate(`document.querySelector('#person-box').hidden`),false);
  await evaluate(`document.querySelector('#play').click()`);await delay(150);assert.equal(await evaluate(`document.querySelector('#play').textContent`),'播放');
  const project=await evaluate(`(async()=>{const{openStore}=await import('./src/project-store.js');return(await(await openStore()).load()).project})()`);assert.equal(project.captionStyle.preset,'outline');assert.equal(project.segments[0].volume,.35);
  const screenshot=await call('Page.captureScreenshot');await writeFile('/tmp/eduvideo-v5-captions.png',Buffer.from(screenshot.data,'base64'));
  console.log('Continuous playback editing, selectable model manager, API privacy fields and richer caption styles: passed');
}finally{socket.close();}
