import {SPEECH_MODELS,modelById,browserModelSupported} from './speech-models.js';

const DB='eduvideo-speech-models',STORE='models';
const openDb=()=>new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
async function transaction(mode,callback){const db=await openDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode);const request=callback(tx.objectStore(STORE));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.onerror=()=>reject(tx.error);});}finally{db.close();}}
export const browserModelStatuses=async()=>{const db=await openDb();try{const keys=await new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAllKeys();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return SPEECH_MODELS.map(model=>({...model,installed:keys.includes(model.id)}));}finally{db.close();}};
export const getBrowserModel=id=>transaction('readonly',store=>store.get(modelById(id).id));
export const removeBrowserModel=id=>transaction('readwrite',store=>store.delete(modelById(id).id));
export async function importBrowserModel(id,file){if(!browserModelSupported(id))throw new Error('瀏覽器離線模型僅支援 tiny、base、small');if(!(file instanceof Blob)||file.size<modelById(id).bytes*.75)throw new Error('模型檔案大小不正確');await transaction('readwrite',store=>store.put(file,id));}
export async function downloadBrowserModel(id,{signal,progress=()=>{}}={}){const model=modelById(id);if(!model.browser)throw new Error('此模型太大，請改用桌面版或 API');const response=await fetch(model.url,{signal});if(!response.ok||!response.body)throw new Error(`模型下載失敗（HTTP ${response.status}）`);const reader=response.body.getReader(),chunks=[];let received=0;while(true){const{done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.length;progress({received,total:Number(response.headers.get('content-length'))||model.bytes,percent:Math.min(99,Math.round(received/model.bytes*100))});}const blob=new Blob(chunks);if(blob.size<model.bytes*.9)throw new Error('模型下載不完整');await transaction('readwrite',store=>store.put(blob,id));progress({received:blob.size,total:blob.size,percent:100});}

let modulePromise,currentModel=null,currentInstance=0;const outputListeners=new Set();
function whisperModule(){if(modulePromise)return modulePromise;modulePromise=new Promise((resolve,reject)=>{globalThis.Module={locateFile:name=>new URL(`../vendor/whisper-web/${name}`,import.meta.url).href,print:(...parts)=>{const line=parts.join(' ');for(const listener of outputListeners)listener(line);},printErr:(...parts)=>{const line=parts.join(' ');for(const listener of outputListeners)listener(line);},onRuntimeInitialized:()=>resolve(globalThis.Module)};const script=document.createElement('script');script.src=new URL('../vendor/whisper-web/libmain.js',import.meta.url).href;script.onerror=()=>reject(new Error('無法載入瀏覽器辨識引擎'));document.head.append(script);});return modulePromise;}
async function runWhisper(modelId,model,audio,language){const engine=await whisperModule();if(currentModel!==modelId){if(currentInstance)engine.free(currentInstance);try{engine.FS_unlink('whisper.bin');}catch{}engine.FS_createDataFile('/','whisper.bin',new Uint8Array(model),true,true);currentInstance=engine.init('whisper.bin');if(!currentInstance)throw new Error('模型無法載入');currentModel=modelId;}return new Promise((resolve,reject)=>{const cues=[],listener=line=>{const match=line.match(/\[(\d+):(\d+):(\d+[.]\d+)\s+-->\s+(\d+):(\d+):(\d+[.]\d+)\]\s*(.*)/);if(match){const stamp=(h,m,s)=>Number(h)*3600+Number(m)*60+Number(s),text=match[7].trim();if(text)cues.push({start:stamp(match[1],match[2],match[3]),end:stamp(match[4],match[5],match[6]),text});}if(line.includes('whisper_print_timings:')){cleanup();resolve(cues);}},cleanup=()=>{clearTimeout(timer);outputListeners.delete(listener);},timer=setTimeout(()=>{cleanup();reject(new Error('瀏覽器辨識逾時；請改用較小模型、桌面版或 API'));},10*60*1000);outputListeners.add(listener);const result=engine.full_default(currentInstance,audio,language==='auto'?'auto':language,Math.max(1,Math.min(8,navigator.hardwareConcurrency||4)),false);if(result){cleanup();reject(new Error('瀏覽器辨識失敗'));}});}
function resample(channel,fromRate,toRate=16000){if(fromRate===toRate)return new Float32Array(channel);const length=Math.round(channel.length*toRate/fromRate),output=new Float32Array(length),ratio=fromRate/toRate;for(let i=0;i<length;i++){const at=i*ratio,left=Math.floor(at),right=Math.min(channel.length-1,left+1),mix=at-left;output[i]=channel[left]*(1-mix)+channel[right]*mix;}return output;}
async function decode(blob){const context=new AudioContext({sampleRate:16000});try{const audio=await context.decodeAudioData(await blob.arrayBuffer()),mono=new Float32Array(audio.length);for(let channel=0;channel<audio.numberOfChannels;channel++){const data=audio.getChannelData(channel);for(let i=0;i<data.length;i++)mono[i]+=data[i]/audio.numberOfChannels;}return resample(mono,audio.sampleRate);}finally{await context.close();}}
export async function transcribeInBrowser(blob,{modelId='tiny',language='zh'}={}){if(!crossOriginIsolated)throw new Error('瀏覽器離線辨識需要跨來源隔離；請使用 EduVideo 本機伺服器或桌面版');const stored=await getBrowserModel(modelId);if(!(stored instanceof Blob))throw new Error('請先下載或匯入所選的瀏覽器模型');const[model,audio]=await Promise.all([stored.arrayBuffer(),decode(blob)]),result=await runWhisper(modelId,model,audio,language);return result.map(item=>({id:crypto.randomUUID(),...item}));}
