import {SPEECH_MODELS,formatModelSize} from './speech-models.js';
import {mountCaptionWorkspace} from './caption-workspace.js';

export function mountCaptions(actions){
  const $=id=>document.getElementById(id),inspector=document.querySelector('.edit-inspector'),pane=document.createElement('section');pane.className='caption-controls';
  pane.innerHTML=`<h2>字幕</h2><p class="hint">辨識後會自動切成適合閱讀的短句；字幕跟隨片段裁切與變速。</p>
    <label>辨識方式<select id="caption-provider"><option value="local">離線模型（不上傳）</option><option value="api">語音辨識 API</option></select></label>
    <div id="caption-local-settings"><label>離線模型<select id="caption-model"></select></label><div id="caption-model-detail" class="model-detail"></div><div class="model-actions"><button id="caption-model-download">下載模型</button><button id="caption-model-remove">移除</button><button id="caption-model-import">匯入模型檔</button></div><input id="caption-model-file" type="file" accept=".bin" hidden></div>
    <div id="caption-api-settings" hidden><label>API 服務<select id="caption-api-preset"><option value="gpt-4o-transcribe">OpenAI · GPT-4o Transcribe（文字最準，時間為估算）</option><option value="gpt-4o-transcribe-diarize">OpenAI · GPT-4o Transcribe Diarize（含時間段）</option><option value="whisper-1">OpenAI · Whisper-1（含時間段）</option><option value="custom">自訂 OpenAI 相容模型</option></select></label><label>API 網址<input id="caption-api-endpoint" type="url" value="https://api.openai.com/v1/audio/transcriptions"></label><label>模型名稱<input id="caption-api-model" value="gpt-4o-transcribe"></label><label>API Key<input id="caption-api-key" type="password" autocomplete="off" placeholder="只保留到關閉此頁"></label><p class="hint">音訊會送至你設定的服務；Key 不會寫入專案或瀏覽器儲存空間。</p></div>
    <label>辨識語言<select id="caption-language"><option value="zh">中文</option><option value="en">English</option><option value="ja">日本語</option><option value="auto">自動偵測</option></select></label>
    <label>斷句方式<select id="caption-phrasing"><option value="natural">自然子句（句尾、轉折與停頓）</option><option value="sentence">完整句子（保留較長句）</option></select></label><p class="hint">依語言邊界斷句，不硬切字數。含逐字時間時保留語音停頓；只有整段時間的結果會估算分句時間，請搭配播放校對。</p>
    <div class="two-columns"><button id="caption-recognize">辨識此片段</button><button id="caption-recognize-all">辨識全部</button></div><p id="caption-progress" role="status" class="hint">選擇模型後即可辨識。</p><button id="caption-cancel" hidden>取消目前工作</button>
    <div class="two-columns"><button id="caption-add">＋ 新增字幕</button><button id="caption-import">匯入 SRT</button><button id="caption-export">匯出 SRT</button><button id="caption-clear">清除本段</button></div><input id="caption-file" type="file" accept=".srt" hidden>
    <details class="caption-appearance" open><summary>字幕外觀</summary><label><input id="caption-enabled" type="checkbox" checked> 顯示並燒錄字幕</label><label>樣式<select id="caption-preset"><option value="plate">深色底板</option><option value="outline">文字外框</option><option value="shadow">柔和陰影</option><option value="minimal">純文字</option><option value="brand">品牌色側條</option></select></label><div class="caption-style-preview" id="caption-style-preview">字幕樣式預覽</div><div class="two-columns"><label>字級<select id="caption-size"><option value="26">小</option><option value="32" selected>中</option><option value="40">大</option><option value="52">特大</option></select></label><label>位置<select id="caption-position"><option value="bottom">下方</option><option value="middle">中央</option><option value="top">上方</option></select></label></div><div class="two-columns"><label>文字色<input id="caption-color" type="color" value="#ffffff"></label><label>強調色<input id="caption-accentColor" type="color" value="#6aa9ff"></label><label>底色<input id="caption-backgroundColor" type="color" value="#000000"></label><label>外框色<input id="caption-outlineColor" type="color" value="#000000"></label></div><label>底板透明度<input id="caption-backgroundOpacity" type="range" min="0" max="1" step=".05" value=".72"></label><label>外框粗細<input id="caption-outlineWidth" type="range" min="0" max="8" step="1" value="3"></label><label>字重<select id="caption-fontWeight"><option value="500">一般</option><option value="600" selected>中粗</option><option value="700">粗體</option><option value="800">特粗</option></select></label></details><div id="caption-list"></div>`;
  inspector.append(pane);const tab=document.createElement('button');tab.id='properties-captions';tab.textContent='字幕';tab.setAttribute('aria-pressed','false');document.querySelector('.property-tabs').append(tab);tab.onclick=()=>{inspector.dataset.tab='captions';document.querySelector('.inspector').scrollTop=0;for(const b of document.querySelectorAll('.property-tabs button'))b.setAttribute('aria-pressed',String(b===tab));};
  const recognition=document.createElement('details');recognition.className='caption-recognition';recognition.innerHTML='<summary>自動辨識與模型</summary>';const first=$('caption-provider').closest('label');first.before(recognition);let n=first;while(n){const next=n.nextElementSibling;recognition.append(n);if(n.id==='caption-cancel')break;n=next;}
  const native=Boolean(window.studioNative?.speechModels);for(const model of SPEECH_MODELS.filter(item=>native||item.browser))$('caption-model').append(new Option(`${model.label} · ${formatModelSize(model.bytes)}`,model.id));$('caption-model').value=native?'large-v3-turbo-q5_0':'tiny';
  $('caption-list').before(Object.assign(document.createElement('button'),{id:'caption-resegment',textContent:'重新自然斷句（全片）',onclick:()=>actions.resegment($('caption-phrasing').value)}));
  $('caption-list').before(Object.assign(document.createElement('button'),{id:'caption-rebuild-timing',textContent:'從音訊重新辨識（修復時間）',onclick:()=>{recognition.open=true;actions.recognize(true,settings());}}));
  $('caption-list').before(Object.assign(document.createElement('p'),{className:'hint',textContent:'重新斷句保留現有文字；舊字幕若有時間錯位，請從音訊重新辨識。此操作會取代字幕，可復原。'}));
  const workspace=mountCaptionWorkspace($('caption-list'),actions);pane.querySelector('.caption-appearance').open=false;
  pane.append($('caption-list'));
  let models=[],modelBusy=false,hadCues;
  const selectedModel=()=>models.find(item=>item.id===$('caption-model').value);
  const settings=()=>({provider:$('caption-provider').value,modelId:$('caption-model').value,language:$('caption-language').value,phrasing:$('caption-phrasing').value,endpoint:$('caption-api-endpoint').value,apiModel:$('caption-api-model').value,apiKey:$('caption-api-key').value});
  function modelDetail(){const model=selectedModel()||SPEECH_MODELS.find(item=>item.id===$('caption-model').value);if(!model)return;$('caption-model-detail').innerHTML=`<strong>${model.installed?'✓ 已下載':'尚未下載'}</strong><span>${model.description}</span>`;$('caption-model-download').hidden=model.installed;$('caption-model-remove').hidden=!model.installed;$('caption-model-import').hidden=native||!model.browser;}
  async function refreshModels(){try{models=await actions.modelStatuses();modelDetail();}catch(error){$('caption-progress').textContent=`無法讀取模型：${error.message}`;}}
  const providerChanged=()=>{$('caption-local-settings').hidden=$('caption-provider').value!=='local';$('caption-api-settings').hidden=$('caption-provider').value!=='api';};$('caption-provider').onchange=providerChanged;
  $('caption-api-preset').onchange=()=>{const value=$('caption-api-preset').value;if(value!=='custom')$('caption-api-model').value=value;};$('caption-model').onchange=modelDetail;
  $('caption-model-download').onclick=async()=>{modelBusy=true;$('caption-cancel').hidden=false;try{await actions.downloadModel($('caption-model').value,value=>$('caption-progress').textContent=`下載模型 ${value.percent}%`);await refreshModels();$('caption-progress').textContent='模型已下載並通過檢查。';}catch(error){$('caption-progress').textContent=error.name==='AbortError'?'已取消模型下載。':`模型下載失敗：${error.message}`;}finally{modelBusy=false;$('caption-cancel').hidden=true;}};
  $('caption-model-remove').onclick=async()=>{if(!confirm('移除這個離線模型？之後可重新下載。'))return;await actions.removeModel($('caption-model').value);await refreshModels();};$('caption-model-import').onclick=()=>$('caption-model-file').click();$('caption-model-file').onchange=async()=>{const file=$('caption-model-file').files[0];if(!file)return;await actions.importModel($('caption-model').value,file);await refreshModels();};
  for(const id of ['properties-clip','properties-person'])$(id).addEventListener('click',()=>tab.setAttribute('aria-pressed','false'));
  $('caption-recognize').onclick=()=>actions.recognize(false,settings());$('caption-recognize-all').onclick=()=>actions.recognize(true,settings());$('caption-cancel').onclick=()=>modelBusy?actions.cancelModel():actions.cancel();$('caption-add').onclick=()=>actions.add();$('caption-clear').onclick=()=>actions.clear();$('caption-import').onclick=()=>$('caption-file').click();$('caption-file').onchange=()=>actions.import($('caption-file').files[0]);$('caption-export').onclick=()=>actions.export();
  const styleKeys=['enabled','preset','size','position','color','accentColor','backgroundColor','backgroundOpacity','outlineColor','outlineWidth','fontWeight'];for(const key of styleKeys)$(`caption-${key}`).onchange=()=>{const input=$(`caption-${key}`),value=input.type==='checkbox'?input.checked:input.type==='range'||key==='size'?Number(input.value):input.value;actions.style(key,value);updatePreview();};
  function updatePreview(){const preview=$('caption-style-preview'),preset=$('caption-preset').value;preview.dataset.preset=preset;preview.style.setProperty('--caption-color',$('caption-color').value);preview.style.setProperty('--caption-bg',$('caption-backgroundColor').value);preview.style.setProperty('--caption-accent',$('caption-accentColor').value);preview.style.setProperty('--caption-outline',$('caption-outlineColor').value);preview.style.setProperty('--caption-opacity',$('caption-backgroundOpacity').value);preview.style.setProperty('--caption-stroke',`${$('caption-outlineWidth').value}px`);preview.style.fontWeight=$('caption-fontWeight').value;}
  providerChanged();refreshModels();
  return {sync(project,index,busy){const segment=project.segments[index],style=project.captionStyle||{};for(const id of ['caption-add','caption-clear','caption-import','caption-export'])$(id).disabled=busy||!segment;for(const id of ['caption-recognize','caption-recognize-all'])$(id).disabled=busy||modelBusy||!segment;
    for(const key of styleKeys){const input=$(`caption-${key}`),fallback={enabled:true,preset:'plate',size:32,position:'bottom',color:'#ffffff',accentColor:'#6aa9ff',backgroundColor:'#000000',backgroundOpacity:.72,outlineColor:'#000000',outlineWidth:3,fontWeight:'600'}[key];if(document.activeElement!==input){if(input.type==='checkbox')input.checked=style[key]??fallback;else input.value=style[key]??fallback;}input.disabled=busy;}updatePreview();
    workspace.sync(project,index,busy);$('caption-resegment').disabled=busy||!project.segments.some(s=>s.captions?.length);$('caption-rebuild-timing').disabled=busy||modelBusy||!segment;const hasCues=project.segments.some(s=>s.captions?.length);if(hadCues!==hasCues){hadCues=hasCues;recognition.open=!hadCues;}
  },update:time=>workspace.update(time),progress(text){$('caption-progress').textContent=text;},working(value){$('caption-cancel').hidden=!value;if(value)recognition.open=true;},refreshModels};
}
