import {mediaPreview} from './media-preview.js';
export function mountLibrary(actions){const list=document.getElementById('media-list'),bar=document.createElement('section');bar.id='library-tools';bar.innerHTML='<input id="media-search" type="search" placeholder="搜尋素材…" aria-label="搜尋素材"><select id="media-filter" aria-label="素材篩選"><option value="all">全部素材</option><option value="unused">未使用</option><option value="used">使用中</option></select><span id="media-summary" class="hint"></span>';list.before(bar);let state,openId;
  const $=id=>document.getElementById(id);$('media-search').oninput=()=>render();$('media-filter').onchange=()=>render();
  function render(){if(!state)return;const{project,assets,busy}=state,query=$('media-search').value.toLowerCase(),filter=$('media-filter').value;const shown=project.takes.filter(t=>{const used=project.segments.filter(s=>s.takeId===t.id).length;return (t.name||`錄製 ${project.takes.indexOf(t)+1}`).toLowerCase().includes(query)&&(filter==='all'||(filter==='used'?used>0:used===0));});
    const bytes=project.takes.reduce((n,t)=>n+(assets[t.id]?.screen.size||0)+(assets[t.id]?.camera.size||0),0);$('media-summary').textContent=`${project.takes.length} 份素材 · ${(bytes/1048576).toFixed(1)} MB`;
    list.replaceChildren(...shown.map(t=>{const i=project.takes.indexOf(t),used=project.segments.filter(s=>s.takeId===t.id).length,item=document.createElement('details');item.className='media-card';item.open=openId===t.id;const summary=document.createElement('summary'),img=new Image(),title=document.createElement('strong'),meta=document.createElement('span');title.textContent=t.name||`錄製 ${i+1}`;img.alt='素材預覽';meta.className='hint';meta.textContent=`${t.duration.toFixed(1)} 秒 · ${used?`使用 ${used} 次`:'未使用'}`;summary.append(img,title,meta);item.append(summary);item.ontoggle=()=>{if(item.open)openId=t.id;};
      if(assets[t.id])mediaPreview(assets[t.id]).then(p=>{img.src=p.poster;}).catch(()=>img.remove());
      const name=document.createElement('input');name.value=t.name||`錄製 ${i+1}`;name.setAttribute('aria-label','素材名稱');name.maxLength=100;name.onchange=()=>actions.rename(t.id,name.value);name.disabled=busy;item.append(name);
      for(const[label,key]of[['定位使用處','locate'],['加入時間軸','append'],['下載原始素材','download'],['移除素材','remove']]){const button=document.createElement('button');button.textContent=label;button.disabled=busy||(key==='locate'&&!used);button.onclick=()=>actions[key](t.id);item.append(button);}return item;}));
    if(!shown.length){const empty=document.createElement('p');empty.className='hint';empty.textContent=project.takes.length?'沒有符合條件的素材。':'尚無素材，錄製後會出現在這裡。';list.append(empty);}
  }
  return {sync(project,assets,busy){if(state?.project===project&&state?.assets===assets&&state?.busy===busy)return;state={project,assets,busy};render();}};
}
