export function mountStudio() {
  document.querySelector('#studio').innerHTML = `
    <header><strong><b class="brand">E</b> EduVideo</strong><nav aria-label="工作區"><button id="mode-record" aria-pressed="true">◉ 錄製</button><button id="mode-edit" aria-pressed="false">✂ 剪輯</button></nav><span></span><button id="toggle-notes">講者筆記</button><button id="export" class="primary">匯出影片 ↗</button></header>
    <main><aside class="library"><h2 id="library-title">簡報頁面</h2><button id="import">＋ 匯入簡報</button><input id="file" type="file" accept="application/pdf,image/*" hidden><div id="slides"></div><div id="media-list"></div><p class="hint" id="library-hint">支援 PDF 與圖片<br>切換頁面即可開始解說</p></aside>
    <section class="viewer"><div class="viewer-heading"><span id="viewer-title">錄製預覽</span><span class="hint">16:9 · 720p</span></div><div class="stage-space"><div class="stage"><canvas id="canvas" width="1280" height="720"></canvas><video id="camera" autoplay muted playsinline hidden title="拖曳移動人像預覽"></video><div id="countdown" hidden></div></div></div>
    <div class="slide-tools"><button id="prev" aria-label="上一頁">‹</button><span id="page-count">0 / 0</span><button id="next" aria-label="下一頁">›</button><span class="divider"></span><button id="clear">清除標記</button></div>
    <div class="record-dock"><label>錄製來源<select id="source"><option value="slides">簡報與標記</option><option value="screen">視窗／螢幕</option></select></label><button id="devices">相機與麥克風</button><div class="mic"><span>麥克風</span><meter id="mic-meter" min="0" max="1" value="0"></meter></div><button id="record" class="record" disabled>開始錄製</button><span id="clock">00:00</span></div></section>
    <aside class="inspector"><div class="record-inspector"><h2>講者筆記</h2><p class="hint">大綱與逐字稿，只有你看得到。</p><textarea id="notes" placeholder="先說明主題，再開始示範…"></textarea><h2>人像預覽</h2><label class="hint">預覽大小<input id="camera-size" type="range" min="15" max="38" value="22"></label><p class="hint">鏡像顯示 · 拖曳調整位置<br>原始人像另外保存</p></div><div class="edit-inspector"><h2>片段設定</h2><p class="hint">簡報、人像和聲音同步裁切</p><label>素材起點（秒）<input id="start" type="number" min="0" step="0.1"></label><label>素材終點（秒）<input id="end" type="number" min="0" step="0.1"></label><button id="trim">套用精確裁切</button><p class="hint">也可以拖曳時間軸片段兩端。</p></div></aside></main>
    <section id="timeline"><div class="timeline-toolbar"><button id="play">播放</button><span id="position">0.00 / 0.00 秒</span><span class="spacer"></span><button id="split" title="S：分割">✂ 分割</button><button id="delete" title="Delete：刪除">刪除</button><button id="undo" title="⌘Z：復原">↶ 復原</button></div><input id="seek" aria-label="播放頭" type="range" min="0" max="0" step="0.01" value="0"><div class="track"><span class="track-label">▣ 簡報<br>◉ 人像<br>♫ 聲音</span><div id="segments"></div></div><p class="hint" id="timeline-empty">完成錄製後，素材會出現在這裡。</p></section>
    <footer><span id="status" role="status">正在讀取專案…</span><span class="hint" id="shortcut-hint">簡報與人像分開保存</span></footer><video class="source" id="screen-video" playsinline></video><video class="source" id="camera-video" playsinline></video>`;
}
