import {snapPoints,snapTime} from './timeline-snap.js';import {projectDuration} from './edit-project.js';import {outputCues} from './captions.js';
export function mountTimeline({getState,seek}){const $=id=>document.getElementById(id),content=$('timeline-content'),ruler=$('time-ruler');
  const toggle=document.createElement('button');toggle.id='snap-toggle';toggle.textContent='磁吸 開';toggle.setAttribute('aria-pressed','true');toggle.title='貼齊剪接點、字幕邊界與聲音停頓；拖曳時按 Alt 暫停磁吸';document.querySelector('.timeline-toolbar').append(toggle);let enabled=true;
  toggle.onclick=()=>{enabled=!enabled;toggle.textContent=`磁吸 ${enabled?'開':'關'}`;toggle.setAttribute('aria-pressed',String(enabled));};
  const captions=document.createElement('div');captions.id='caption-track';content.append(captions);
  const head=document.createElement('div');head.id='timeline-playhead';head.tabIndex=0;head.setAttribute('role','slider');head.setAttribute('aria-label','時間軸播放頭');head.innerHTML='<span class="playhead-cap"></span><span class="snap-label"></span>';content.append(head);let dragging=false,signature='';
  function magnet(value,event){const{project,audio}=getState(),duration=projectDuration(project),width=$('segments').getBoundingClientRect().width;return enabled&&!event?.altKey?snapTime(value,snapPoints(project,audio),duration/Math.max(1,width)*8):{time:value,snapped:false};}
  function move(e){const{project}=getState(),r=$('segments').getBoundingClientRect(),duration=projectDuration(project);if(!duration)return;const target=magnet(Math.max(0,Math.min(duration,(e.clientX-r.left)/r.width*duration)),e);head.dataset.snapped=String(target.snapped);head.querySelector('.snap-label').textContent=target.snapped?{cut:'剪接點',audio:'聲音邊界',caption:'字幕邊界'}[target.kind]:'';seek(target.time);}
  for(const target of [ruler,head]){target.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();head.focus({preventScroll:true});dragging=true;target.setPointerCapture(e.pointerId);move(e);};target.onpointermove=e=>{if(dragging)move(e);};target.onpointerup=e=>{if(dragging)move(e);dragging=false;head.dataset.snapped='false';};target.onpointercancel=()=>{dragging=false;head.dataset.snapped='false';};}
  head.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.stopPropagation();e.preventDefault();const{time,project}=getState();seek(Math.max(0,Math.min(projectDuration(project),time+(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?1:1/30))));}};
  function update(){const{project,time}=getState(),duration=projectDuration(project),r=$('segments').getBoundingClientRect(),c=content.getBoundingClientRect();head.hidden=!duration;head.style.left=`${r.left-c.left+(duration?time/duration:0)*r.width}px`;head.setAttribute('aria-valuemin','0');head.setAttribute('aria-valuemax',String(duration));head.setAttribute('aria-valuenow',String(time));
    const cues=outputCues(project),key=JSON.stringify(cues);if(signature!==key){signature=key;captions.replaceChildren(...cues.map(cue=>{const b=document.createElement('button');b.textContent=cue.text;b.title=cue.text;b.style.left=`${cue.start/duration*100}%`;b.style.width=`${(cue.end-cue.start)/duration*100}%`;b.onclick=()=>{seek(cue.start);$('properties-captions')?.click();};return b;}));}captions.hidden=!cues.length;
  }
  new ResizeObserver(update).observe(content);
  return {update,enabled:()=>enabled,snapSource(value,points,tolerance,event){return enabled&&!event?.altKey?snapTime(value,points.map(time=>({time,kind:'audio'})),tolerance).time:value;}};
}
